import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Work | Skybound Solutions',
    description:
        'Explore our portfolio of AI-powered solutions — from operations platforms and voice agents to iOS apps and word games. Real projects with real results.',
};

const projects = [
    {
        title: 'AI-Powered Operations Platform',
        client: 'Medical Training Company',
        description:
            'End-to-end operations platform for a medical training organization. Features a real-time dashboard, automated AHA roster generation, compliance tracking, and ANNIE — a 24/7 AI voice agent handling inbound calls, appointment booking, and intelligent escalation.',
        challenge: 'Manual processes consuming 20+ hours per week on compliance, scheduling, and call handling.',
        solution: 'Built a React dashboard with Firebase backend, integrated ElevenLabs-powered voice agent, and automated compliance workflows.',
        results: ['99% reduction in admin time', '24/7 AI call handling', 'Automated AHA compliance'],
        tags: ['React', 'Firebase', 'ElevenLabs', 'Twilio', 'Cloud Functions'],
        slug: 'operations-platform',
        status: 'case-study',
    },
    {
        title: 'Proxle',
        client: 'Skybound Product',
        description:
            'AI-powered word puzzle game with contextual hints and dynamic difficulty. Players guess a 5-letter word using natural language clues generated by AI, creating a unique blend of word games and conversational AI.',
        challenge: 'Create an engaging word game that demonstrates practical AI integration patterns.',
        solution: 'Built with React and Gemini API. AI generates contextual, dynamic hints that adapt to player progress — no two games play the same way.',
        results: ['Live on web', 'AI hint engine', 'Reusable AI integration patterns'],
        tags: ['React', 'Gemini API', 'Game Design', 'TypeScript'],
        slug: 'proxle',
        status: 'coming-soon',
    },
    {
        title: 'MYIEP',
        client: 'Skybound Product',
        description:
            'iOS app helping parents navigate Individualized Education Program (IEP) documents. Upload complex IEP PDFs and get AI-powered analysis, plain-language summaries, and actionable insights for parent-teacher conferences.',
        challenge: 'IEP documents are dense, legal, and overwhelming for parents trying to advocate for their children.',
        solution: 'React Native iOS app with on-device AI preprocessing for privacy, cloud AI for deep analysis, and a clean interface that makes IEP data accessible.',
        results: ['In development', 'On-device AI for privacy', 'App Store submission planned'],
        tags: ['React Native', 'Apple Foundation Models', 'Cloud AI', 'iOS'],
        slug: 'myiep',
        status: 'coming-soon',
    },
    {
        title: 'Point-of-Sale System',
        client: 'Youth Sports Organization',
        description:
            'Custom e-commerce and point-of-sale platform for a youth sports booster club. Handles online ordering, event-day sales, inventory tracking, and financial reporting — replacing a patchwork of spreadsheets and manual processes.',
        challenge: 'Disorganized sales tracking across multiple fundraising events with no centralized inventory or reporting.',
        solution: 'Next.js application with Stripe payment integration, real-time inventory management, and automated financial reports.',
        results: ['Unified sales platform', 'Real-time inventory', 'Automated reporting'],
        tags: ['Next.js', 'Stripe', 'Firebase', 'TypeScript'],
        slug: 'pos-system',
        status: 'coming-soon',
    },
];

const capabilities = [
    'AI Agent Development',
    'Conversational AI & NLP',
    'Web Applications',
    'iOS & Mobile Apps',
    'Real-Time Dashboards',
    'Cloud Infrastructure',
    'API Integrations',
    'Workflow Automation',
    'E-Commerce Platforms',
    'Data Analytics',
    'DevOps & CI/CD',
    'Security & Compliance',
];

export default function WorkPage() {
    return (
        <div style={{ paddingTop: 'var(--header-height)' }}>
            {/* Header */}
            <section className="section" style={{ paddingBottom: 40 }}>
                <div className="container" style={{ textAlign: 'center', maxWidth: 800 }}>
                    <div className="section-label">Our Work</div>
                    <h1 className="heading-xl" style={{ marginBottom: 16 }}>
                        Real Solutions.{' '}
                        <span className="text-gradient">Real Results.</span>
                    </h1>
                    <p className="text-lg">
                        A selection of projects that showcase our capabilities — from AI-powered platforms to consumer apps.
                    </p>
                </div>
            </section>

            {/* Projects */}
            <section className="section section-dark" style={{ paddingTop: 20 }}>
                <div className="container" style={{ maxWidth: 900 }}>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '3rem' }}>
                        {projects.map((project) => (
                            <div
                                key={project.slug}
                                className="card card-glass"
                                style={{ padding: '2.5rem' }}
                            >
                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 8, marginBottom: 8 }}>
                                    <h2 className="heading-md">{project.title}</h2>
                                    <span style={{ color: '#64748b', fontSize: '0.85rem', fontStyle: 'italic' }}>
                                        {project.client}
                                    </span>
                                </div>

                                <p className="text-base" style={{ marginBottom: 20 }}>
                                    {project.description}
                                </p>

                                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: 20, marginBottom: 20 }}>
                                    <div>
                                        <h4 style={{ color: 'var(--sky-blue)', fontSize: '0.85rem', fontWeight: 600, marginBottom: 6 }}>Challenge</h4>
                                        <p style={{ color: '#94a3b8', fontSize: '0.9rem' }}>{project.challenge}</p>
                                    </div>
                                    <div>
                                        <h4 style={{ color: 'var(--electric-teal)', fontSize: '0.85rem', fontWeight: 600, marginBottom: 6 }}>Solution</h4>
                                        <p style={{ color: '#94a3b8', fontSize: '0.9rem' }}>{project.solution}</p>
                                    </div>
                                </div>

                                {/* Results */}
                                <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 20 }}>
                                    {project.results.map((r) => (
                                        <span
                                            key={r}
                                            style={{
                                                padding: '4px 12px',
                                                borderRadius: 6,
                                                background: 'rgba(0, 212, 170, 0.1)',
                                                color: 'var(--electric-teal)',
                                                fontSize: '0.8rem',
                                                fontWeight: 600,
                                            }}
                                        >
                                            {r}
                                        </span>
                                    ))}
                                </div>

                                {/* Tags + CTA */}
                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 }}>
                                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                                        {project.tags.map((tag) => (
                                            <span
                                                key={tag}
                                                style={{
                                                    padding: '3px 10px',
                                                    borderRadius: 6,
                                                    background: 'rgba(0,122,255,0.1)',
                                                    color: 'var(--sky-blue)',
                                                    fontSize: '0.7rem',
                                                    fontWeight: 500,
                                                }}
                                            >
                                                {tag}
                                            </span>
                                        ))}
                                    </div>
                                    <Link
                                        href={`/work/${project.slug}`}
                                        style={{
                                            color: project.status === 'case-study' ? 'var(--sky-blue)' : '#64748b',
                                            fontSize: '0.9rem',
                                            fontWeight: 500,
                                        }}
                                    >
                                        {project.status === 'case-study' ? 'View Case Study →' : 'Case Study Coming Soon'}
                                    </Link>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* Capabilities Grid */}
            <section className="section">
                <div className="container" style={{ maxWidth: 800 }}>
                    <div className="section-header">
                        <div className="section-label">Capabilities</div>
                        <h2 className="heading-lg">What We Work With</h2>
                    </div>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10, justifyContent: 'center' }}>
                        {capabilities.map((cap) => (
                            <span
                                key={cap}
                                className="card card-glass"
                                style={{
                                    padding: '8px 20px',
                                    fontSize: '0.9rem',
                                    color: '#94a3b8',
                                    fontWeight: 500,
                                }}
                            >
                                {cap}
                            </span>
                        ))}
                    </div>
                </div>
            </section>

            {/* CTA */}
            <section className="section section-dark" style={{ textAlign: 'center' }}>
                <div className="container" style={{ maxWidth: 600 }}>
                    <h2 className="heading-lg" style={{ marginBottom: 16 }}>
                        Have a Similar Problem?
                    </h2>
                    <p className="text-lg" style={{ marginBottom: 32 }}>
                        Let&apos;s talk about your project. Every engagement starts with a free discovery call.
                    </p>
                    <Link href="/contact" className="btn btn-teal btn-lg">
                        Book a Discovery Call →
                    </Link>
                </div>
            </section>
        </div>
    );
}
